import Head from "next/head";
import Headers from "./Headers";
import About from "./About";
import Skills from "./Skills";
import Portfolio from "./Portfolio";
import Sertificate from "./Sertificate";
import Contact from "./Contact";
import Footer from "./Footer";
import Navigation from "./Navigation";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio | Abdul Majid Abdalah</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Headers />
        <About />
        <Skills />
        <Portfolio />
        <Sertificate />
        <Contact />
        <Footer />
        <Navigation />
      </main>
    </>
  );
}
